# Arcade Power Control Using ESPHome
#  - 2022 Ben Parmeter

esphome:
  name: arcadepower

esp8266:
  board: nodemcu

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Arcadepower Fallback Hotspot"
    password: "vDHB3iE8wqma"

web_server:
  port: 80
  local: true

captive_portal:

switch:
  - platform: gpio
    name: "Host PC Power Switch"
    id: hostrelay
    pin: D1
    inverted: true
    icon: "mdi:set-top-box"
    restore_mode: ALWAYS_OFF
    on_turn_on:
    - delay: 1000ms
    - switch.turn_off: hostrelay

  - platform: gpio
    name: "Power Strip Switch"
    id: accrelay
    pin: D2
    inverted: true
    icon: "mdi:power-socket-us"
    restore_mode: ALWAYS_OFF

binary_sensor:
  - platform: gpio
    name: "Arcade Main Power Switch"
    id: mainswitch
    icon: "mdi:controller-classic"
    pin:
      number: D0
      mode:
        input: true
        pulldown: true
    filters:
      - delayed_off: 700ms  # Debounce for very noisy switch
    on_press:  # When Main Power Switch is turned to ON 
      then:
      - if:
          condition:  # If power strip is currently off, then turn on
            switch.is_off: accrelay
          then:
          - switch.turn_on: hostrelay
          - switch.turn_on: accrelay
    on_release:  # When Main Power Switch is turned to OFF
      then:
      - if:
          condition:  # If power strip is currently on, then turn off
            switch.is_on: accrelay
          then:
          - switch.turn_on: hostrelay
          - delay: 5000ms
          - switch.turn_off: accrelay
